chore(tests): do not upgrade pytest to the latest version
flaky, and its pytest plugin, is incompatible with pytest >= 8.1.0; when
running with this version, it fails with:

```
ImportError: cannot import name 'call_runtest_hook' from '_pytest.runner' (/usr/local/lib/python3.12/site-packages/_pytest/runner.py)
```

Listing pytest in requirements.txt has the practical effect that it gets
upgraded to the latest version. This commit removes pytest from the
requirements.txt file keeping the version installed in the test
container.

Changelog: None
Ticket: None

Signed-off-by: Fabio Tranchitella <fabio.tranchitella@northern.tech>